version: "3"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ports:
      - "8080:8080"

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    depends_on:
      database:
        condition: service_healthy
volumes:
  data:
